# Generated by Django 5.0.4 on 2024-05-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_alter_srsdocuments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='srsdocuments',
            name='thread_id',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
