# Generated by Django 5.0.4 on 2024-05-12 13:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_alter_srsdocuments_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SRSDocuments',
            new_name='SRSDocument',
        ),
    ]
