# Generated by Django 5.0.4 on 2024-05-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_rename_srsdocuments_srsdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='srsdocument',
            name='changed_document',
            field=models.JSONField(null=True),
        ),
    ]
